title: Lisa Harmon's Portfolio
description: A collection of writing samples to showcase my experience and skills as a professional technical communicator.
theme: just-the-docs

url: https://LisaHarmon.github.io/portfolio

aux_links:
  Template Repository: https://github.com/LisaHarmon/portfolio
